module.exports = {
  COLOR_DATA: {
    Red: 'RED',
    Orange: 'ORANGE',
    Yellow: 'YELLOW',
    Green: 'GREEN',
    Blue: 'BLUE',
    Indigo: 'INDIGO',
    Violet: 'VIOLET',
  },
  COLOR_PRICE: {
    Red: 0.5,
    Orange: 0.5,
    Yellow: 0.5,
    Green: 0.5,
    Blue: 0.5,
    Indigo: 0.6,
    Vioconst: 0.6,
  },
  SIZE_DATA: {
    XS: 'XS',
    S: 'S',
    M: 'M',
    L: 'L',
    XL: 'XL',
    XXL: 'XXL',
    XXXL: 'XXXL',
  },
  SIZE_PRICE: {
    XS: 0.1,
    S: 0.1,
    M: 0.2,
    L: 0.2,
    XL: 0.3,
    XXL: 0.4,
    XXXL: 0.4,
  },
  FABRIC_DATA: {
    Wool: 'WOOL',
    Cotton: 'COTTON',
    Polyester: 'POLYESTER',
    Rayon: 'RAYON',
    Linen: 'LINEN',
    Cashmere: 'CASHEMERE',
    Silk: 'SILK',
  },
  FABRIC_PRICE: {
    Wool: 0.8,
    Cotton: 0.95,
    Polyester: 0.99,
    Rayon: 1.2,
    Linen: 2.7,
    Cashmere: 4.6,
    Silk: 7.2,
  },
};
